// lib/superagent/config.ts

import type {
  SuperAgentConfig,
  SuperAgentSkillDefinition,
} from "./types"

export const SUPERAGENT_CONFIG: SuperAgentConfig = {
  identity: {
    displayName: "EduAI Claw",
    engineAlias: "EduAI Claw — modo PicoClaw",
    internalName: "eduai_claw",
    version: "0.1.0",
    inspiration: {
      sandboxStyle: "PicoClaw",
      skillsStyle: "OpenClaw",
    },
  },
  mode: "observe_social_anticipate",
  status: "idle",
  features: {
    autonomyEnabled: true,
    socialLayerEnabled: true,
    anticipationEnabled: true,
    draftCreationEnabled: true,
    routingEnabled: true,
    selfModificationEnabled: false,
    productionWriteEnabled: false,
  },
  limits: {
    maxSuggestionsPerCycle: 3,
    maxDraftsPerCycle: 2,
    maxSkillsPerCycle: 4,
    allowPrivateChatInjection: false,
    allowProductionOverwrite: false,
    allowSecretInspection: false,
  },
}

export const SUPERAGENT_SKILLS: SuperAgentSkillDefinition[] = [
  {
    name: "observe_user_context",
    description: "Observa el contexto actual del usuario y la página activa.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["chat", "social", "unknown"],
  },
  {
    name: "route_to_best_agent",
    description: "Selecciona el agente más adecuado según la intención detectada.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: [
      "chat",
      "educador",
      "investigador",
      "matematico",
      "paper",
      "imagenes",
      "audio",
      "examen",
      "unknown",
    ],
  },
  {
    name: "summarize_goal",
    description: "Resume el objetivo actual del usuario para mejorar el contexto.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["chat", "social", "drafts", "unknown"],
  },
  {
    name: "optimize_prompt",
    description: "Mejora prompts antes de enviarlos a otros agentes.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: [
      "educador",
      "investigador",
      "matematico",
      "paper",
      "imagenes",
      "audio",
      "examen",
      "unknown",
    ],
  },
  {
    name: "repair_failed_call",
    description: "Intenta recuperar o reprocesar llamadas fallidas de agentes.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: [
      "chat",
      "educador",
      "investigador",
      "matematico",
      "paper",
      "imagenes",
      "audio",
      "examen",
      "unknown",
    ],
  },
  {
    name: "save_memory_snapshot",
    description: "Guarda un resumen útil del contexto del usuario.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["chat", "social", "drafts", "unknown"],
  },
  {
    name: "suggest_next_step",
    description: "Sugiere el siguiente paso más útil para el usuario.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["chat", "social", "drafts", "unknown"],
  },
  {
    name: "agent_health_check",
    description: "Revisa el estado lógico de los agentes disponibles.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: [
      "educador",
      "investigador",
      "matematico",
      "paper",
      "imagenes",
      "audio",
      "examen",
      "unknown",
    ],
  },
  {
    name: "spawn_agent_discussion",
    description: "Inicia una conversación entre agentes en el chat social interno.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["social"],
  },
  {
    name: "extract_ideas_from_social_chat",
    description: "Extrae ideas útiles desde conversaciones internas entre agentes.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["social", "drafts"],
  },
  {
    name: "anticipate_user_next_need",
    description: "Anticipa posibles necesidades futuras del usuario.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["drafts", "unknown"],
  },
  {
    name: "create_draft_file",
    description: "Crea borradores seguros sin tocar archivos productivos.",
    enabled: true,
    safeByDefault: true,
    allowedTargets: ["drafts"],
  },
]
