import type { BrainAICapability } from "@/lib/brain-ai/types"

export const BRAIN_AI_CAPABILITIES: BrainAICapability[] = [
  {
    id: "brain.signal-analyzer",
    label: "Signal Analyzer",
    region: "brain",
    state: "ready",
    locality: "local",
    engine: "Brain AI v5",
    productionStage: "VALIDATING",
    description: "Detecta modalidad, intención, complejidad y necesidad de memoria antes de activar modelos.",
    dependencies: [],
    risks: ["clasificación heurística en Shadow Mode"],
  },
  {
    id: "brain.cognitive-router",
    label: "Cognitive Router",
    region: "brain",
    state: "ready",
    locality: "local",
    engine: "Brain AI v5",
    productionStage: "VALIDATING",
    description: "Selecciona FAST_MEMORY, STANDARD_REASONING, DEEP_COGNITION, RETRIEVAL, VALIDATION, REPAIR o ACTION.",
    dependencies: ["brain.signal-analyzer"],
    risks: ["requiere evaluación continua contra resultados reales"],
  },
  {
    id: "brain.world-model",
    label: "World Model",
    region: "brain",
    state: "candidate",
    locality: "local",
    engine: "Brain AI v5 deterministic preview",
    productionStage: "CANDIDATE",
    description: "Predice riesgos, fallbacks y consecuencias de un plan antes de ejecutar capacidades costosas.",
    dependencies: ["brain.cognitive-router"],
    risks: ["predicciones heurísticas; todavía no aprende de ejecuciones reales"],
  },
  {
    id: "brain.reflection",
    label: "Reflection + Recovery",
    region: "brain",
    state: "candidate",
    locality: "hybrid",
    engine: "Brain AI v5",
    productionStage: "CANDIDATE",
    description: "Evalúa resultado, activa VALIDATION/REPAIR y registra señales para optimización posterior.",
    dependencies: ["brain.cognitive-router"],
    risks: ["validación semántica profunda depende de un LLM disponible"],
  },
  {
    id: "memory.working",
    label: "Working Memory",
    region: "memory",
    state: "ready",
    locality: "local",
    engine: "browser memory",
    productionStage: "VALIDATING",
    description: "Estado cognitivo temporal y planes de la ejecución actual; no persiste contenido sensible automáticamente.",
    dependencies: [],
    risks: [],
  },
  {
    id: "memory.long-term",
    label: "Long-term Memory",
    region: "memory",
    state: "candidate",
    locality: "hybrid",
    engine: "Supabase/Postgres + pgvector",
    productionStage: "CANDIDATE",
    description: "Memoria episódica, semántica, canónica, procedural, reflection y curricular con política explícita de lectura/escritura.",
    dependencies: ["Supabase", "RLS", "embeddings"],
    risks: ["requiere esquema de memoria y políticas RLS definitivas antes de persistir desde Brain AI"],
  },
  {
    id: "text.local-llm",
    label: "Local LLM",
    region: "text",
    modality: "text",
    state: "candidate",
    locality: "local",
    engine: "LiteRT-LM · Gemma/Qwen readiness",
    productionStage: "CANDIDATE",
    description: "Generación local para reasoning estándar cuando el dispositivo y el runtime lo permitan.",
    dependencies: ["WebGPU", "LiteRT-LM"],
    risks: ["Qwen web aún sujeto a soporte JS; Gemma requiere memoria considerable"],
  },
  {
    id: "text.cloud-llm",
    label: "Cloud LLM / AI Core",
    region: "text",
    modality: "text",
    state: "ready",
    locality: "cloud",
    engine: "EduAI AI Core",
    productionStage: "VALIDATED",
    description: "Reasoning profundo, structured output y fallback cuando la ruta local no alcanza calidad o capacidad.",
    dependencies: ["AI Core", "proveedores configurados"],
    risks: ["latencia y costo variable"],
  },
  {
    id: "audio.vad",
    label: "Voice Activity / Silence Gate",
    region: "audio",
    modality: "audio",
    state: "ready",
    locality: "local",
    engine: "Whisper ASR v1.5 waveform quality pipeline",
    productionStage: "VALIDATING",
    description: "Detecta pausas y límites de voz para segmentar audio sin enviar la señal a la nube.",
    dependencies: [],
    risks: ["VAD energético, no diarización"],
  },
  {
    id: "audio.whisper",
    label: "Whisper Tiny INT8",
    region: "audio",
    modality: "audio",
    state: "ready",
    locality: "local",
    engine: "LiteRT.js · Worker · Router V3",
    productionStage: "VALIDATING",
    description: "Speech-to-text multilingüe, long-form, timestamps, VAD adaptativo, fuzzy merge y exportación TXT/SRT/VTT.",
    dependencies: ["WASM o WebGPU", "LiteRT.js"],
    risks: ["calidad limitada por Whisper Tiny INT8"],
  },
  {
    id: "audio.tts",
    label: "Text-to-Speech",
    region: "audio",
    modality: "audio",
    state: "candidate",
    locality: "hybrid",
    engine: "Browser SpeechSynthesis / EduAI voice stack",
    productionStage: "CANDIDATE",
    description: "Salida de voz para pruebas conversacionales; Model Lab validará voces, latencia e idioma antes de llevarlo a MIRA.",
    dependencies: ["speechSynthesis o proveedor TTS"],
    risks: ["voces locales dependen del sistema operativo/navegador"],
  },
  {
    id: "image.classification",
    label: "MobileNet V3",
    region: "image",
    modality: "image",
    state: "ready",
    locality: "local",
    engine: "LiteRT.js · FP32/INT8 · Router V3",
    productionStage: "VALIDATING",
    description: "Clasificación visual local y benchmark WASM/WebGPU con cache y compiled model pool.",
    dependencies: ["LiteRT.js"],
    risks: ["clasificación general; no sustituye visión multimodal completa"],
  },
  {
    id: "image.ocr",
    label: "OCR / Document Vision",
    region: "image",
    modality: "image",
    state: "candidate",
    locality: "hybrid",
    engine: "EduAI document pipeline",
    productionStage: "CANDIDATE",
    description: "Extracción de texto y estructura para guías, evaluaciones y documentos con validación de ecuaciones e imágenes.",
    dependencies: ["pipeline documental"],
    risks: ["calidad depende del tipo de documento"],
  },
  {
    id: "image.vision",
    label: "Multimodal Vision",
    region: "image",
    modality: "image",
    state: "candidate",
    locality: "cloud",
    engine: "AI Core vision models",
    productionStage: "CANDIDATE",
    description: "Comprensión visual de alto nivel cuando clasificación/OCR local no son suficientes.",
    dependencies: ["AI Core"],
    risks: ["costo/latencia cloud"],
  },
  {
    id: "video.analysis",
    label: "Video Analysis",
    region: "video",
    modality: "video",
    state: "candidate",
    locality: "hybrid",
    engine: "frames + Whisper + vision",
    productionStage: "CANDIDATE",
    description: "Descompone video en audio, transcript y frames para fusionar contexto temporal y visual.",
    dependencies: ["audio.whisper", "image.vision"],
    risks: ["coste de muestreo de frames y visión"],
  },
  {
    id: "video.generation",
    label: "Video Generation Router",
    region: "video",
    modality: "video",
    state: "ready",
    locality: "cloud",
    engine: "EduAI Video Router",
    productionStage: "VALIDATED",
    description: "Enrutamiento de proveedores/modelos de video ya observable desde Model Lab.",
    dependencies: ["proveedores de video"],
    risks: ["costo y disponibilidad externos"],
  },
  {
    id: "router.local-ai",
    label: "Local AI Router V3",
    region: "router",
    state: "ready",
    locality: "local",
    engine: "LiteRT Router V3",
    productionStage: "VALIDATING",
    description: "Perfil por modelo/dispositivo para decidir WASM/WebGPU y recordar incompatibilidades determinísticas.",
    dependencies: ["telemetría local"],
    risks: [],
  },
  {
    id: "router.brain-v5",
    label: "Brain Router V5",
    region: "router",
    state: "candidate",
    locality: "hybrid",
    engine: "Brain AI Cognitive Router",
    productionStage: "CANDIDATE",
    description: "Selecciona capacidad local/híbrida/cloud a nivel de tarea, no solo de backend.",
    dependencies: ["brain.cognitive-router", "capability registry"],
    risks: ["se mantiene en Shadow Mode hasta comparar decisiones con EduAI real"],
  },
  {
    id: "tools.eduai",
    label: "EduAI Tools / Agents",
    region: "tools",
    modality: "tool",
    state: "ready",
    locality: "hybrid",
    engine: "EduAI agents + APIs",
    productionStage: "VALIDATED",
    description: "Capa de acciones para crear, consultar, transformar o guardar resultados después de governance.",
    dependencies: ["auth", "policy guard"],
    risks: ["acciones mutables requieren autorización explícita"],
  },
  {
    id: "multimodal.fusion",
    label: "Multimodal Fusion",
    region: "multimodal",
    state: "candidate",
    locality: "hybrid",
    engine: "Brain AI context fusion",
    productionStage: "CANDIDATE",
    description: "Combina texto, audio, imagen y video en un único plan sin procesar modalidades irrelevantes.",
    dependencies: ["brain.signal-analyzer", "brain.cognitive-router"],
    risks: ["necesita benchmark multimodal y reglas de presupuesto"],
  },
]

export function getBrainAICapability(id: string) {
  return BRAIN_AI_CAPABILITIES.find(capability => capability.id === id) || null
}

export function getBrainAICapabilitiesByRegion(region: BrainAICapability["region"]) {
  return BRAIN_AI_CAPABILITIES.filter(capability => capability.region === region)
}
